liip_imagine:
    driver: gd
    web_root: %web_root%
    cache_prefix:  uploads/media/cache
    cache_clearer: false
    filter_sets:
        avatar:
            quality: 75
            filters:
                thumbnail: { size: [166, 166], mode: outbound }